services:
  # ============================================================================
  # SPARK CLUSTER
  # ============================================================================

  spark-master:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark-master
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    env_file:
      - .env
    ports:
      - "${SPARK_MASTER_UI_PORT:-8080}:8080"
      - "${SPARK_MASTER_PORT:-7077}:7077"
    volumes:
      - /mnt/c/Users/italo/WSL_DATA/lakehouse-data:/data
      - ./spark_jobs:/opt/spark/jobs
      - ./configs:/opt/spark/configs
      - ./results:/opt/spark/results
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-worker-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-2}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-4g}
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - /mnt/c/Users/italo/WSL_DATA/lakehouse-data:/data
      - ./spark_jobs:/opt/spark/jobs
      - ./results:/opt/spark/results
    depends_on:
      - spark-master
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-worker-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark-worker
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-2}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-4g}
    env_file:
      - .env
    ports:
      - "8082:8081"
    volumes:
      - /mnt/c/Users/italo/WSL_DATA/lakehouse-data:/data
      - ./spark_jobs:/opt/spark/jobs
      - ./results:/opt/spark/results
    depends_on:
      - spark-master
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================================================
  # TPC-H DATA GENERATOR
  # ============================================================================

  tpchgen:
    build:
      context: .
      dockerfile: docker/Dockerfile.tpchgen
    container_name: tpchgen
    env_file:
      - .env
    volumes:
      - /mnt/c/Users/italo/WSL_DATA/lakehouse-data:/data
      - ./scripts:/app/scripts
    networks:
      - lakehouse-net
    profiles:
      - datagen

networks:
  lakehouse-net:
    driver: bridge
    name: lakehouse-network
